# Generated by Django 3.1.5 on 2021-01-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_number', models.CharField(help_text='Name of the Camera.', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude of the Camera Location.', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude of the Camera Location.', max_digits=10)),
                ('url', models.CharField(help_text='Functioning RTSP link(rtsp://localhost:8554/ds-test) or Path to Local Video(/home/user/vid.mp4.', max_length=400)),
                ('plate_threshold', models.DecimalField(decimal_places=1, default=0.5, help_text='Threshold for Plate Detection.', max_digits=10)),
                ('character_threshold', models.DecimalField(decimal_places=1, default=0.5, help_text='Threshold for Character Detection and Recognition.', max_digits=10)),
                ('plate_interval', models.IntegerField(default=4, help_text='Inference Interval for Plate Detection')),
                ('roi', models.DecimalField(decimal_places=2, default=0.6, help_text='Percentage of ROI(y) for plate detection. 0.6 of 1920x1080 means detections happen only inside (1920,(1-0.6)x1080) = (1920,432).', max_digits=10)),
                ('nireq', models.IntegerField(default=1, help_text='Number of Inference Requests for plate detection. It is usually the number of streams.')),
                ('video_display', models.BooleanField(default=False, help_text='Tick to turn it on. Enables video display with bounding boxes and FPS for debugging purposes. Remember to disable before Deployment.')),
            ],
            options={
                'db_table': 'camera_config',
            },
        ),
        migrations.CreateModel(
            name='LicensePlates',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('camera_number', models.CharField(max_length=100)),
                ('number_plate_number', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('fullimage', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'license_plates',
                'managed': True,
            },
        ),
    ]
